name: Build nakkikuningas Godot Project

on:
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - name: linux
            file: nakkikuningas
          - name: windows
            file: nakkikuningas.exe
          - name: mac
            file: nakkikuningas.zip
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Build
        id: build
        uses: tjlaxs/build-godot-action@master
        with:
          name: ${{ matrix.platform.file }}
          preset: ${{ matrix.platform.name }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform.file }} - ${{ matrix.platform.name }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
